name: simple_state_machine
description: A simple implementation of an extended state machine. Implement own conditions. No variable support (yet).
version: 1.0.2
repository: https://github.com/IvoSchols/dart-state-machine

environment:
  sdk: '>=2.17.6 <3.0.0'
  
dependencies:
  analyzer: ^4.3.1
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
