name: state_machine
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'
  
dependencies:
  binary_expression_tree:
    git: https://github.com/IvoSchols/dart-binary-expression-tree

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  test_coverage: ^0.5.0
